version: "3.8"

services:
  streamlit-app:
    # image: streamlit-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - mysql
      - qdrant
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Karan@04
      MYSQL_DATABASE: academic_chatbot
      QDRANT_URL: http://qdrant:6333

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Karan@04
      MYSQL_DATABASE: academic_chatbot
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  mysql_data:
  qdrant_storage:
